### PR TITLE
Fixes an issue with the count in the frequency table and an edge case…

### PR DESCRIPTION
**Pull request by thomaspiller**
… where the lower bound was assigned a null value.

### CODE REVIEW

**Review by fxi — COMMENTED** [review]
Great !
We could add a comment to explain why/how prepend + remove are done ?
`[1,2,<max>] -> [<min>,1,2]`

**Comment by thomaspiller** [comment]
Sure, the situation causing the `from = null` problem was as follows:

- number of bins = 1
- all features have the same value.

In the SQL query this gave:
- `attr_min = n`
- `attr_max = n`
- `attr_bin_max = n`
- `bins = {n}`

Before the patch:

```sql
array_remove(
     array_prepend(attr_min, bins),
     attr_bin_max
  )
```
Result: `{n} -> {n, n} -> {}`

After the patch:

```sql
array_prepend(
    attr_min,
    array_remove(bins, attr_bin_max)
  )
```
Result: `{n} -> {} -> {n} `

**Comment by fxi** [comment]
Yep, that's what the patch fixes, I was mentioning a single line comment – not specific to the single bin case – to hint our future self what's going on with the _remove inside the _prepend. But I will add it myself after the merge.

**Review by fxi — APPROVED** [review]

**Comment by thomaspiller** [comment]
It wasn't very clear to me. But indeed, it is more relevant to add a comment in the `.sql` file.

**Pull request merged**
